### ISSUE TITLE
Add "Re-Generate" calendar feature to the model

### ISSUE THREAD

**Issue by Danielsio** [itayf9/Plan_It_Enigne_1.0#34]
Add "Re-Generate" calendar feature to the model.

This feature needs to be implemented somehow, to allow users to regenerate study period and remember the progress of the last one

**Comment by itayf9** [comment]
@oshriFadlon1 @Danielsio  Feel free to suggest how to approach this problem.

**Comment by Danielsio** [comment]
I agree with @oshriFadlon1 about sending some boolean flag to indicate if the user wanted regular scan or Regenerate scan

1. declare a field at the user db to some boolean with name of "isRegeneratePossible", while this fiels is true then we know the user has active studyPlan that we can regenerate according to the new parameters

2. now we need to figure out what part of the old sessions is not needed anymore.. (tricky part)
if we collect all the ols sessions and filter out the unrelevent ones you will stay with the new sessions that needs to be re-inserted in the user calendar let's call those "sessionsToCreate"

3. we still need to evaluate timeslots of user cause it might change, so fetch timeslots (good thing we have method for that :)

4. send  "sessionsToCreate" and the "timeslots" to the generate plan method and return.

5. dont forget to maintaine "isRegeneratePossible" field.

**Comment by itayf9** [comment]
@Danielsio Regarding the boolean "isRegeneratePossible", we should we hold it in the database? Because Regeneration is alway possible (it will act just like a regular "generate" if the user generates for the first time.).

**Comment by oshriFadlon1** [comment]
I was thinking of sending from the front. Boolean to know what type of generate the user choose.
If it's from the generate button
or the Regenerate button,
And according to that  we can handle his events.
If the generate variety as we have been doing until now.
If it's Regenerate,
He has already learned. we Fetching from the database the courses and remove the subjectes the already learned. 
And then do generate with the subjectes left for the time frame we got now

**Comment by Danielsio** [comment]
> @Danielsio Regarding the boolean "isRegeneratePossible", we should we hold it in the database? Because Regeneration is alway possible (it will act just like a regular "generate" if the user generates for the first time.).

i see, in that case you are correct. i have nothing to add.

**Comment by itayf9** [comment]
Anyway, my Idea was to direct both of the "generate" and "regenerate" requests to the same endpoint "/scan" and to add an `isRegenerate` flag to distinguish between them.

**Comment by Danielsio** [comment]
Also since it's simple to retrieve the events that isn't relevant for Re-generate process, i think those event should be erased.
so in addition to the steps above add steps for:
1. create method that receives list of google events and sends delete request to google calendar service.
2. call the method during the regenerate process - probably after regenerate is successful
